codeunit 73209575 "Split Payment Handler"
{
    procedure ProcessSplitPayment(var SplitPaymentRec: Record "BLRSplitPaymentChange")
    var
        NewLine: Record "BLRSplitPaymentChange";
        AlreadySelected: Record "BLRSplitPaymentChange";
        PaymentSchedule2Rec: Record "BLRPaymentSchedule2";
        UnselectedPaymentSeries: Text[100];
        TotalAmount: Decimal;
        TotalVATAmount: Decimal;
        TotalAmountInclVAT: Decimal;
        CurrentItemType: Text[250];
        IsItemSelected: Boolean;
    begin
        // -----------------------------------------
        // Calculate and insert new line for remaining unselected items
        // -----------------------------------------
        UnselectedPaymentSeries := '';
        Clear(TotalAmount);
        Clear(TotalVATAmount);
        Clear(TotalAmountInclVAT);

        PaymentSchedule2Rec.Reset();
        PaymentSchedule2Rec.SetRange("BLRContract ID", SplitPaymentRec."BLRContract ID");
        PaymentSchedule2Rec.SetRange("BLRPayment Series", SplitPaymentRec."BLRSplit Payment Series");

        if PaymentSchedule2Rec.FindSet() then
            repeat
                CurrentItemType := PaymentSchedule2Rec."BLRSecondary Item Type";
                IsItemSelected := false;

                // First check the record being modified (may not be saved yet)
                if SplitPaymentRec."BLRSecondary Item Type" <> '' then
                    if StrPos(SplitPaymentRec."BLRSecondary Item Type", CurrentItemType) <> 0 then
                        IsItemSelected := true;

                // If not found there, examine other existing lines in table
                if not IsItemSelected then begin
                    AlreadySelected.Reset();
                    AlreadySelected.SetRange("BLRContract ID", SplitPaymentRec."BLRContract ID");
                    AlreadySelected.SetRange("BLRSplit Payment Series", SplitPaymentRec."BLRSplit Payment Series");
                    // exclude the current record from the search
                    if SplitPaymentRec."BLREntry No." <> 0 then
                        AlreadySelected.SetFilter("BLREntry No.", '<>%1', SplitPaymentRec."BLREntry No.");

                    AlreadySelected.SetFilter("BLRSecondary Item Type", '@*' + CurrentItemType + '*');
                    if not AlreadySelected.IsEmpty then
                        IsItemSelected := true;
                end;

                // Only add if not already selected
                if not IsItemSelected then begin
                    if UnselectedPaymentSeries <> '' then
                        UnselectedPaymentSeries += ', ';

                    UnselectedPaymentSeries += CurrentItemType;
                    TotalAmount += PaymentSchedule2Rec."BLRAmount";
                    TotalVATAmount += PaymentSchedule2Rec."BLRVAT Amount";
                    TotalAmountInclVAT += PaymentSchedule2Rec."BLRAmount Including VAT";
                end;
            until PaymentSchedule2Rec.Next() = 0;

        // -----------------------------------------
        // Create new line if there are unselected items
        // -----------------------------------------
        if UnselectedPaymentSeries <> '' then begin
            NewLine.Init();
            NewLine."BLRContract ID" := SplitPaymentRec."BLRContract ID";
            NewLine."BLRTenant Id" := SplitPaymentRec."BLRTenant Id";
            NewLine."BLRSplit Payment Series" := SplitPaymentRec."BLRSplit Payment Series";
            NewLine."BLRSecondary Item Type" := UnselectedPaymentSeries;
            NewLine."BLRSplit Amount" := TotalAmount;
            NewLine."BLRSplit VAT Amount" := TotalVATAmount;
            NewLine."BLRSplit Amount Including VAT" := TotalAmountInclVAT;
            // Entry No. will be auto-generated by the system
            NewLine.Insert(true); // Use Insert(true) to allow triggers
        end;
    end;
}
