codeunit 50921 "Split Payment Handler"
{
    procedure ProcessSplitPayment(var SplitPaymentRec: Record "Split Payment Change")
    var
        NewLine: Record "Split Payment Change";
        AlreadySelected: Record "Split Payment Change";
        PaymentSchedule2Rec: Record "Payment Schedule2";
        UnselectedPaymentSeries: Text[100];
        TotalAmount: Decimal;
        TotalVATAmount: Decimal;
        TotalAmountInclVAT: Decimal;
        CurrentItemType: Text[250];
        IsItemSelected: Boolean;
    begin
        // -----------------------------------------
        // Calculate and insert new line for remaining unselected items
        // -----------------------------------------
        UnselectedPaymentSeries := '';
        Clear(TotalAmount);
        Clear(TotalVATAmount);
        Clear(TotalAmountInclVAT);

        PaymentSchedule2Rec.Reset();
        PaymentSchedule2Rec.SetRange("Contract ID", SplitPaymentRec."Contract ID");
        PaymentSchedule2Rec.SetRange("Payment Series", SplitPaymentRec."Split Payment Series");

        if PaymentSchedule2Rec.FindSet() then
            repeat
                CurrentItemType := PaymentSchedule2Rec."Secondary Item Type";
                IsItemSelected := false;

                // First check the record being modified (may not be saved yet)
                if SplitPaymentRec."Secondary Item Type" <> '' then
                    if StrPos(SplitPaymentRec."Secondary Item Type", CurrentItemType) <> 0 then
                        IsItemSelected := true;

                // If not found there, examine other existing lines in table
                if not IsItemSelected then begin
                    AlreadySelected.Reset();
                    AlreadySelected.SetRange("Contract ID", SplitPaymentRec."Contract ID");
                    AlreadySelected.SetRange("Split Payment Series", SplitPaymentRec."Split Payment Series");
                    // exclude the current record from the search
                    if SplitPaymentRec."Entry No." <> 0 then
                        AlreadySelected.SetFilter("Entry No.", '<>%1', SplitPaymentRec."Entry No.");

                    AlreadySelected.SetFilter("Secondary Item Type", '@*' + CurrentItemType + '*');
                    if not AlreadySelected.IsEmpty then
                        IsItemSelected := true;
                end;

                // Only add if not already selected
                if not IsItemSelected then begin
                    if UnselectedPaymentSeries <> '' then
                        UnselectedPaymentSeries += ', ';

                    UnselectedPaymentSeries += CurrentItemType;
                    TotalAmount += PaymentSchedule2Rec.Amount;
                    TotalVATAmount += PaymentSchedule2Rec."VAT Amount";
                    TotalAmountInclVAT += PaymentSchedule2Rec."Amount Including VAT";
                end;
            until PaymentSchedule2Rec.Next() = 0;

        // -----------------------------------------
        // Create new line if there are unselected items
        // -----------------------------------------
        if UnselectedPaymentSeries <> '' then begin
            NewLine.Init();
            NewLine."Contract ID" := SplitPaymentRec."Contract ID";
            NewLine."Tenant Id" := SplitPaymentRec."Tenant Id";
            NewLine."Split Payment Series" := SplitPaymentRec."Split Payment Series";
            NewLine."Secondary Item Type" := UnselectedPaymentSeries;
            NewLine."Split Amount" := TotalAmount;
            NewLine."Split VAT Amount" := TotalVATAmount;
            NewLine."Split Amount Including VAT" := TotalAmountInclVAT;
            // Entry No. will be auto-generated by the system
            NewLine.Insert(true); // Use Insert(true) to allow triggers
        end;
    end;
}
